// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: feder.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_feder_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_feder_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_feder_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_feder_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_feder_2eproto;
namespace milvus {
namespace proto {
namespace feder {
class DescribeSegmentIndexDataRequest;
struct DescribeSegmentIndexDataRequestDefaultTypeInternal;
extern DescribeSegmentIndexDataRequestDefaultTypeInternal _DescribeSegmentIndexDataRequest_default_instance_;
class DescribeSegmentIndexDataResponse;
struct DescribeSegmentIndexDataResponseDefaultTypeInternal;
extern DescribeSegmentIndexDataResponseDefaultTypeInternal _DescribeSegmentIndexDataResponse_default_instance_;
class DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse;
struct DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUseDefaultTypeInternal;
extern DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUseDefaultTypeInternal _DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse_default_instance_;
class FederSegmentSearchResult;
struct FederSegmentSearchResultDefaultTypeInternal;
extern FederSegmentSearchResultDefaultTypeInternal _FederSegmentSearchResult_default_instance_;
class ListIndexedSegmentRequest;
struct ListIndexedSegmentRequestDefaultTypeInternal;
extern ListIndexedSegmentRequestDefaultTypeInternal _ListIndexedSegmentRequest_default_instance_;
class ListIndexedSegmentResponse;
struct ListIndexedSegmentResponseDefaultTypeInternal;
extern ListIndexedSegmentResponseDefaultTypeInternal _ListIndexedSegmentResponse_default_instance_;
class SegmentIndexData;
struct SegmentIndexDataDefaultTypeInternal;
extern SegmentIndexDataDefaultTypeInternal _SegmentIndexData_default_instance_;
}  // namespace feder
}  // namespace proto
}  // namespace milvus
PROTOBUF_NAMESPACE_OPEN
template<> ::milvus::proto::feder::DescribeSegmentIndexDataRequest* Arena::CreateMaybeMessage<::milvus::proto::feder::DescribeSegmentIndexDataRequest>(Arena*);
template<> ::milvus::proto::feder::DescribeSegmentIndexDataResponse* Arena::CreateMaybeMessage<::milvus::proto::feder::DescribeSegmentIndexDataResponse>(Arena*);
template<> ::milvus::proto::feder::DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse* Arena::CreateMaybeMessage<::milvus::proto::feder::DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse>(Arena*);
template<> ::milvus::proto::feder::FederSegmentSearchResult* Arena::CreateMaybeMessage<::milvus::proto::feder::FederSegmentSearchResult>(Arena*);
template<> ::milvus::proto::feder::ListIndexedSegmentRequest* Arena::CreateMaybeMessage<::milvus::proto::feder::ListIndexedSegmentRequest>(Arena*);
template<> ::milvus::proto::feder::ListIndexedSegmentResponse* Arena::CreateMaybeMessage<::milvus::proto::feder::ListIndexedSegmentResponse>(Arena*);
template<> ::milvus::proto::feder::SegmentIndexData* Arena::CreateMaybeMessage<::milvus::proto::feder::SegmentIndexData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace milvus {
namespace proto {
namespace feder {

// ===================================================================

class SegmentIndexData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:milvus.proto.feder.SegmentIndexData) */ {
 public:
  inline SegmentIndexData() : SegmentIndexData(nullptr) {}
  ~SegmentIndexData() override;
  explicit PROTOBUF_CONSTEXPR SegmentIndexData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SegmentIndexData(const SegmentIndexData& from);
  SegmentIndexData(SegmentIndexData&& from) noexcept
    : SegmentIndexData() {
    *this = ::std::move(from);
  }

  inline SegmentIndexData& operator=(const SegmentIndexData& from) {
    CopyFrom(from);
    return *this;
  }
  inline SegmentIndexData& operator=(SegmentIndexData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SegmentIndexData& default_instance() {
    return *internal_default_instance();
  }
  static inline const SegmentIndexData* internal_default_instance() {
    return reinterpret_cast<const SegmentIndexData*>(
               &_SegmentIndexData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SegmentIndexData& a, SegmentIndexData& b) {
    a.Swap(&b);
  }
  inline void Swap(SegmentIndexData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SegmentIndexData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SegmentIndexData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SegmentIndexData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SegmentIndexData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SegmentIndexData& from) {
    SegmentIndexData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SegmentIndexData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "milvus.proto.feder.SegmentIndexData";
  }
  protected:
  explicit SegmentIndexData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIndexDataFieldNumber = 2,
    kSegmentIDFieldNumber = 1,
  };
  // string index_data = 2;
  void clear_index_data();
  const std::string& index_data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_index_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_index_data();
  PROTOBUF_NODISCARD std::string* release_index_data();
  void set_allocated_index_data(std::string* index_data);
  private:
  const std::string& _internal_index_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_index_data(const std::string& value);
  std::string* _internal_mutable_index_data();
  public:

  // int64 segmentID = 1;
  void clear_segmentid();
  int64_t segmentid() const;
  void set_segmentid(int64_t value);
  private:
  int64_t _internal_segmentid() const;
  void _internal_set_segmentid(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:milvus.proto.feder.SegmentIndexData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr index_data_;
    int64_t segmentid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_feder_2eproto;
};
// -------------------------------------------------------------------

class FederSegmentSearchResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:milvus.proto.feder.FederSegmentSearchResult) */ {
 public:
  inline FederSegmentSearchResult() : FederSegmentSearchResult(nullptr) {}
  ~FederSegmentSearchResult() override;
  explicit PROTOBUF_CONSTEXPR FederSegmentSearchResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FederSegmentSearchResult(const FederSegmentSearchResult& from);
  FederSegmentSearchResult(FederSegmentSearchResult&& from) noexcept
    : FederSegmentSearchResult() {
    *this = ::std::move(from);
  }

  inline FederSegmentSearchResult& operator=(const FederSegmentSearchResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline FederSegmentSearchResult& operator=(FederSegmentSearchResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FederSegmentSearchResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const FederSegmentSearchResult* internal_default_instance() {
    return reinterpret_cast<const FederSegmentSearchResult*>(
               &_FederSegmentSearchResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(FederSegmentSearchResult& a, FederSegmentSearchResult& b) {
    a.Swap(&b);
  }
  inline void Swap(FederSegmentSearchResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FederSegmentSearchResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FederSegmentSearchResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FederSegmentSearchResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FederSegmentSearchResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FederSegmentSearchResult& from) {
    FederSegmentSearchResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FederSegmentSearchResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "milvus.proto.feder.FederSegmentSearchResult";
  }
  protected:
  explicit FederSegmentSearchResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVisitInfoFieldNumber = 2,
    kSegmentIDFieldNumber = 1,
  };
  // string visit_info = 2;
  void clear_visit_info();
  const std::string& visit_info() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_visit_info(ArgT0&& arg0, ArgT... args);
  std::string* mutable_visit_info();
  PROTOBUF_NODISCARD std::string* release_visit_info();
  void set_allocated_visit_info(std::string* visit_info);
  private:
  const std::string& _internal_visit_info() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_visit_info(const std::string& value);
  std::string* _internal_mutable_visit_info();
  public:

  // int64 segmentID = 1;
  void clear_segmentid();
  int64_t segmentid() const;
  void set_segmentid(int64_t value);
  private:
  int64_t _internal_segmentid() const;
  void _internal_set_segmentid(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:milvus.proto.feder.FederSegmentSearchResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr visit_info_;
    int64_t segmentid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_feder_2eproto;
};
// -------------------------------------------------------------------

class ListIndexedSegmentRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:milvus.proto.feder.ListIndexedSegmentRequest) */ {
 public:
  inline ListIndexedSegmentRequest() : ListIndexedSegmentRequest(nullptr) {}
  ~ListIndexedSegmentRequest() override;
  explicit PROTOBUF_CONSTEXPR ListIndexedSegmentRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ListIndexedSegmentRequest(const ListIndexedSegmentRequest& from);
  ListIndexedSegmentRequest(ListIndexedSegmentRequest&& from) noexcept
    : ListIndexedSegmentRequest() {
    *this = ::std::move(from);
  }

  inline ListIndexedSegmentRequest& operator=(const ListIndexedSegmentRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListIndexedSegmentRequest& operator=(ListIndexedSegmentRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListIndexedSegmentRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ListIndexedSegmentRequest* internal_default_instance() {
    return reinterpret_cast<const ListIndexedSegmentRequest*>(
               &_ListIndexedSegmentRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ListIndexedSegmentRequest& a, ListIndexedSegmentRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ListIndexedSegmentRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListIndexedSegmentRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListIndexedSegmentRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ListIndexedSegmentRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ListIndexedSegmentRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ListIndexedSegmentRequest& from) {
    ListIndexedSegmentRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ListIndexedSegmentRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "milvus.proto.feder.ListIndexedSegmentRequest";
  }
  protected:
  explicit ListIndexedSegmentRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCollectionNameFieldNumber = 2,
    kIndexNameFieldNumber = 3,
    kBaseFieldNumber = 1,
  };
  // string collection_name = 2;
  void clear_collection_name();
  const std::string& collection_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_collection_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_collection_name();
  PROTOBUF_NODISCARD std::string* release_collection_name();
  void set_allocated_collection_name(std::string* collection_name);
  private:
  const std::string& _internal_collection_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_collection_name(const std::string& value);
  std::string* _internal_mutable_collection_name();
  public:

  // string index_name = 3;
  void clear_index_name();
  const std::string& index_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_index_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_index_name();
  PROTOBUF_NODISCARD std::string* release_index_name();
  void set_allocated_index_name(std::string* index_name);
  private:
  const std::string& _internal_index_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_index_name(const std::string& value);
  std::string* _internal_mutable_index_name();
  public:

  // .milvus.proto.common.MsgBase base = 1;
  bool has_base() const;
  private:
  bool _internal_has_base() const;
  public:
  void clear_base();
  const ::milvus::proto::common::MsgBase& base() const;
  PROTOBUF_NODISCARD ::milvus::proto::common::MsgBase* release_base();
  ::milvus::proto::common::MsgBase* mutable_base();
  void set_allocated_base(::milvus::proto::common::MsgBase* base);
  private:
  const ::milvus::proto::common::MsgBase& _internal_base() const;
  ::milvus::proto::common::MsgBase* _internal_mutable_base();
  public:
  void unsafe_arena_set_allocated_base(
      ::milvus::proto::common::MsgBase* base);
  ::milvus::proto::common::MsgBase* unsafe_arena_release_base();

  // @@protoc_insertion_point(class_scope:milvus.proto.feder.ListIndexedSegmentRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr collection_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr index_name_;
    ::milvus::proto::common::MsgBase* base_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_feder_2eproto;
};
// -------------------------------------------------------------------

class ListIndexedSegmentResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:milvus.proto.feder.ListIndexedSegmentResponse) */ {
 public:
  inline ListIndexedSegmentResponse() : ListIndexedSegmentResponse(nullptr) {}
  ~ListIndexedSegmentResponse() override;
  explicit PROTOBUF_CONSTEXPR ListIndexedSegmentResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ListIndexedSegmentResponse(const ListIndexedSegmentResponse& from);
  ListIndexedSegmentResponse(ListIndexedSegmentResponse&& from) noexcept
    : ListIndexedSegmentResponse() {
    *this = ::std::move(from);
  }

  inline ListIndexedSegmentResponse& operator=(const ListIndexedSegmentResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ListIndexedSegmentResponse& operator=(ListIndexedSegmentResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ListIndexedSegmentResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ListIndexedSegmentResponse* internal_default_instance() {
    return reinterpret_cast<const ListIndexedSegmentResponse*>(
               &_ListIndexedSegmentResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ListIndexedSegmentResponse& a, ListIndexedSegmentResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ListIndexedSegmentResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ListIndexedSegmentResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ListIndexedSegmentResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ListIndexedSegmentResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ListIndexedSegmentResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ListIndexedSegmentResponse& from) {
    ListIndexedSegmentResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ListIndexedSegmentResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "milvus.proto.feder.ListIndexedSegmentResponse";
  }
  protected:
  explicit ListIndexedSegmentResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSegmentIDsFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // repeated int64 segmentIDs = 2;
  int segmentids_size() const;
  private:
  int _internal_segmentids_size() const;
  public:
  void clear_segmentids();
  private:
  int64_t _internal_segmentids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      _internal_segmentids() const;
  void _internal_add_segmentids(int64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      _internal_mutable_segmentids();
  public:
  int64_t segmentids(int index) const;
  void set_segmentids(int index, int64_t value);
  void add_segmentids(int64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      segmentids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      mutable_segmentids();

  // .milvus.proto.common.Status status = 1;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  const ::milvus::proto::common::Status& status() const;
  PROTOBUF_NODISCARD ::milvus::proto::common::Status* release_status();
  ::milvus::proto::common::Status* mutable_status();
  void set_allocated_status(::milvus::proto::common::Status* status);
  private:
  const ::milvus::proto::common::Status& _internal_status() const;
  ::milvus::proto::common::Status* _internal_mutable_status();
  public:
  void unsafe_arena_set_allocated_status(
      ::milvus::proto::common::Status* status);
  ::milvus::proto::common::Status* unsafe_arena_release_status();

  // @@protoc_insertion_point(class_scope:milvus.proto.feder.ListIndexedSegmentResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t > segmentids_;
    mutable std::atomic<int> _segmentids_cached_byte_size_;
    ::milvus::proto::common::Status* status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_feder_2eproto;
};
// -------------------------------------------------------------------

class DescribeSegmentIndexDataRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:milvus.proto.feder.DescribeSegmentIndexDataRequest) */ {
 public:
  inline DescribeSegmentIndexDataRequest() : DescribeSegmentIndexDataRequest(nullptr) {}
  ~DescribeSegmentIndexDataRequest() override;
  explicit PROTOBUF_CONSTEXPR DescribeSegmentIndexDataRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DescribeSegmentIndexDataRequest(const DescribeSegmentIndexDataRequest& from);
  DescribeSegmentIndexDataRequest(DescribeSegmentIndexDataRequest&& from) noexcept
    : DescribeSegmentIndexDataRequest() {
    *this = ::std::move(from);
  }

  inline DescribeSegmentIndexDataRequest& operator=(const DescribeSegmentIndexDataRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline DescribeSegmentIndexDataRequest& operator=(DescribeSegmentIndexDataRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DescribeSegmentIndexDataRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const DescribeSegmentIndexDataRequest* internal_default_instance() {
    return reinterpret_cast<const DescribeSegmentIndexDataRequest*>(
               &_DescribeSegmentIndexDataRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(DescribeSegmentIndexDataRequest& a, DescribeSegmentIndexDataRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(DescribeSegmentIndexDataRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DescribeSegmentIndexDataRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DescribeSegmentIndexDataRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DescribeSegmentIndexDataRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DescribeSegmentIndexDataRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DescribeSegmentIndexDataRequest& from) {
    DescribeSegmentIndexDataRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DescribeSegmentIndexDataRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "milvus.proto.feder.DescribeSegmentIndexDataRequest";
  }
  protected:
  explicit DescribeSegmentIndexDataRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSegmentsIDsFieldNumber = 4,
    kCollectionNameFieldNumber = 2,
    kIndexNameFieldNumber = 3,
    kBaseFieldNumber = 1,
  };
  // repeated int64 segmentsIDs = 4;
  int segmentsids_size() const;
  private:
  int _internal_segmentsids_size() const;
  public:
  void clear_segmentsids();
  private:
  int64_t _internal_segmentsids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      _internal_segmentsids() const;
  void _internal_add_segmentsids(int64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      _internal_mutable_segmentsids();
  public:
  int64_t segmentsids(int index) const;
  void set_segmentsids(int index, int64_t value);
  void add_segmentsids(int64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
      segmentsids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
      mutable_segmentsids();

  // string collection_name = 2;
  void clear_collection_name();
  const std::string& collection_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_collection_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_collection_name();
  PROTOBUF_NODISCARD std::string* release_collection_name();
  void set_allocated_collection_name(std::string* collection_name);
  private:
  const std::string& _internal_collection_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_collection_name(const std::string& value);
  std::string* _internal_mutable_collection_name();
  public:

  // string index_name = 3;
  void clear_index_name();
  const std::string& index_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_index_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_index_name();
  PROTOBUF_NODISCARD std::string* release_index_name();
  void set_allocated_index_name(std::string* index_name);
  private:
  const std::string& _internal_index_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_index_name(const std::string& value);
  std::string* _internal_mutable_index_name();
  public:

  // .milvus.proto.common.MsgBase base = 1;
  bool has_base() const;
  private:
  bool _internal_has_base() const;
  public:
  void clear_base();
  const ::milvus::proto::common::MsgBase& base() const;
  PROTOBUF_NODISCARD ::milvus::proto::common::MsgBase* release_base();
  ::milvus::proto::common::MsgBase* mutable_base();
  void set_allocated_base(::milvus::proto::common::MsgBase* base);
  private:
  const ::milvus::proto::common::MsgBase& _internal_base() const;
  ::milvus::proto::common::MsgBase* _internal_mutable_base();
  public:
  void unsafe_arena_set_allocated_base(
      ::milvus::proto::common::MsgBase* base);
  ::milvus::proto::common::MsgBase* unsafe_arena_release_base();

  // @@protoc_insertion_point(class_scope:milvus.proto.feder.DescribeSegmentIndexDataRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t > segmentsids_;
    mutable std::atomic<int> _segmentsids_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr collection_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr index_name_;
    ::milvus::proto::common::MsgBase* base_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_feder_2eproto;
};
// -------------------------------------------------------------------

class DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse, 
    int64_t, ::milvus::proto::feder::SegmentIndexData,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse, 
    int64_t, ::milvus::proto::feder::SegmentIndexData,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse();
  explicit PROTOBUF_CONSTEXPR DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse& other);
  static const DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse*>(&_DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  friend struct ::TableStruct_feder_2eproto;
};

// -------------------------------------------------------------------

class DescribeSegmentIndexDataResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:milvus.proto.feder.DescribeSegmentIndexDataResponse) */ {
 public:
  inline DescribeSegmentIndexDataResponse() : DescribeSegmentIndexDataResponse(nullptr) {}
  ~DescribeSegmentIndexDataResponse() override;
  explicit PROTOBUF_CONSTEXPR DescribeSegmentIndexDataResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DescribeSegmentIndexDataResponse(const DescribeSegmentIndexDataResponse& from);
  DescribeSegmentIndexDataResponse(DescribeSegmentIndexDataResponse&& from) noexcept
    : DescribeSegmentIndexDataResponse() {
    *this = ::std::move(from);
  }

  inline DescribeSegmentIndexDataResponse& operator=(const DescribeSegmentIndexDataResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline DescribeSegmentIndexDataResponse& operator=(DescribeSegmentIndexDataResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DescribeSegmentIndexDataResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const DescribeSegmentIndexDataResponse* internal_default_instance() {
    return reinterpret_cast<const DescribeSegmentIndexDataResponse*>(
               &_DescribeSegmentIndexDataResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(DescribeSegmentIndexDataResponse& a, DescribeSegmentIndexDataResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(DescribeSegmentIndexDataResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DescribeSegmentIndexDataResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DescribeSegmentIndexDataResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DescribeSegmentIndexDataResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DescribeSegmentIndexDataResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DescribeSegmentIndexDataResponse& from) {
    DescribeSegmentIndexDataResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DescribeSegmentIndexDataResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "milvus.proto.feder.DescribeSegmentIndexDataResponse";
  }
  protected:
  explicit DescribeSegmentIndexDataResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kIndexDataFieldNumber = 2,
    kIndexParamsFieldNumber = 3,
    kStatusFieldNumber = 1,
  };
  // map<int64, .milvus.proto.feder.SegmentIndexData> index_data = 2;
  int index_data_size() const;
  private:
  int _internal_index_data_size() const;
  public:
  void clear_index_data();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< int64_t, ::milvus::proto::feder::SegmentIndexData >&
      _internal_index_data() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int64_t, ::milvus::proto::feder::SegmentIndexData >*
      _internal_mutable_index_data();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< int64_t, ::milvus::proto::feder::SegmentIndexData >&
      index_data() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int64_t, ::milvus::proto::feder::SegmentIndexData >*
      mutable_index_data();

  // repeated .milvus.proto.common.KeyValuePair index_params = 3;
  int index_params_size() const;
  private:
  int _internal_index_params_size() const;
  public:
  void clear_index_params();
  ::milvus::proto::common::KeyValuePair* mutable_index_params(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::milvus::proto::common::KeyValuePair >*
      mutable_index_params();
  private:
  const ::milvus::proto::common::KeyValuePair& _internal_index_params(int index) const;
  ::milvus::proto::common::KeyValuePair* _internal_add_index_params();
  public:
  const ::milvus::proto::common::KeyValuePair& index_params(int index) const;
  ::milvus::proto::common::KeyValuePair* add_index_params();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::milvus::proto::common::KeyValuePair >&
      index_params() const;

  // .milvus.proto.common.Status status = 1;
  bool has_status() const;
  private:
  bool _internal_has_status() const;
  public:
  void clear_status();
  const ::milvus::proto::common::Status& status() const;
  PROTOBUF_NODISCARD ::milvus::proto::common::Status* release_status();
  ::milvus::proto::common::Status* mutable_status();
  void set_allocated_status(::milvus::proto::common::Status* status);
  private:
  const ::milvus::proto::common::Status& _internal_status() const;
  ::milvus::proto::common::Status* _internal_mutable_status();
  public:
  void unsafe_arena_set_allocated_status(
      ::milvus::proto::common::Status* status);
  ::milvus::proto::common::Status* unsafe_arena_release_status();

  // @@protoc_insertion_point(class_scope:milvus.proto.feder.DescribeSegmentIndexDataResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::MapField<
        DescribeSegmentIndexDataResponse_IndexDataEntry_DoNotUse,
        int64_t, ::milvus::proto::feder::SegmentIndexData,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT64,
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> index_data_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::milvus::proto::common::KeyValuePair > index_params_;
    ::milvus::proto::common::Status* status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_feder_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SegmentIndexData

// int64 segmentID = 1;
inline void SegmentIndexData::clear_segmentid() {
  _impl_.segmentid_ = int64_t{0};
}
inline int64_t SegmentIndexData::_internal_segmentid() const {
  return _impl_.segmentid_;
}
inline int64_t SegmentIndexData::segmentid() const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.SegmentIndexData.segmentID)
  return _internal_segmentid();
}
inline void SegmentIndexData::_internal_set_segmentid(int64_t value) {
  
  _impl_.segmentid_ = value;
}
inline void SegmentIndexData::set_segmentid(int64_t value) {
  _internal_set_segmentid(value);
  // @@protoc_insertion_point(field_set:milvus.proto.feder.SegmentIndexData.segmentID)
}

// string index_data = 2;
inline void SegmentIndexData::clear_index_data() {
  _impl_.index_data_.ClearToEmpty();
}
inline const std::string& SegmentIndexData::index_data() const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.SegmentIndexData.index_data)
  return _internal_index_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SegmentIndexData::set_index_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.index_data_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:milvus.proto.feder.SegmentIndexData.index_data)
}
inline std::string* SegmentIndexData::mutable_index_data() {
  std::string* _s = _internal_mutable_index_data();
  // @@protoc_insertion_point(field_mutable:milvus.proto.feder.SegmentIndexData.index_data)
  return _s;
}
inline const std::string& SegmentIndexData::_internal_index_data() const {
  return _impl_.index_data_.Get();
}
inline void SegmentIndexData::_internal_set_index_data(const std::string& value) {
  
  _impl_.index_data_.Set(value, GetArenaForAllocation());
}
inline std::string* SegmentIndexData::_internal_mutable_index_data() {
  
  return _impl_.index_data_.Mutable(GetArenaForAllocation());
}
inline std::string* SegmentIndexData::release_index_data() {
  // @@protoc_insertion_point(field_release:milvus.proto.feder.SegmentIndexData.index_data)
  return _impl_.index_data_.Release();
}
inline void SegmentIndexData::set_allocated_index_data(std::string* index_data) {
  if (index_data != nullptr) {
    
  } else {
    
  }
  _impl_.index_data_.SetAllocated(index_data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.index_data_.IsDefault()) {
    _impl_.index_data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:milvus.proto.feder.SegmentIndexData.index_data)
}

// -------------------------------------------------------------------

// FederSegmentSearchResult

// int64 segmentID = 1;
inline void FederSegmentSearchResult::clear_segmentid() {
  _impl_.segmentid_ = int64_t{0};
}
inline int64_t FederSegmentSearchResult::_internal_segmentid() const {
  return _impl_.segmentid_;
}
inline int64_t FederSegmentSearchResult::segmentid() const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.FederSegmentSearchResult.segmentID)
  return _internal_segmentid();
}
inline void FederSegmentSearchResult::_internal_set_segmentid(int64_t value) {
  
  _impl_.segmentid_ = value;
}
inline void FederSegmentSearchResult::set_segmentid(int64_t value) {
  _internal_set_segmentid(value);
  // @@protoc_insertion_point(field_set:milvus.proto.feder.FederSegmentSearchResult.segmentID)
}

// string visit_info = 2;
inline void FederSegmentSearchResult::clear_visit_info() {
  _impl_.visit_info_.ClearToEmpty();
}
inline const std::string& FederSegmentSearchResult::visit_info() const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.FederSegmentSearchResult.visit_info)
  return _internal_visit_info();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FederSegmentSearchResult::set_visit_info(ArgT0&& arg0, ArgT... args) {
 
 _impl_.visit_info_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:milvus.proto.feder.FederSegmentSearchResult.visit_info)
}
inline std::string* FederSegmentSearchResult::mutable_visit_info() {
  std::string* _s = _internal_mutable_visit_info();
  // @@protoc_insertion_point(field_mutable:milvus.proto.feder.FederSegmentSearchResult.visit_info)
  return _s;
}
inline const std::string& FederSegmentSearchResult::_internal_visit_info() const {
  return _impl_.visit_info_.Get();
}
inline void FederSegmentSearchResult::_internal_set_visit_info(const std::string& value) {
  
  _impl_.visit_info_.Set(value, GetArenaForAllocation());
}
inline std::string* FederSegmentSearchResult::_internal_mutable_visit_info() {
  
  return _impl_.visit_info_.Mutable(GetArenaForAllocation());
}
inline std::string* FederSegmentSearchResult::release_visit_info() {
  // @@protoc_insertion_point(field_release:milvus.proto.feder.FederSegmentSearchResult.visit_info)
  return _impl_.visit_info_.Release();
}
inline void FederSegmentSearchResult::set_allocated_visit_info(std::string* visit_info) {
  if (visit_info != nullptr) {
    
  } else {
    
  }
  _impl_.visit_info_.SetAllocated(visit_info, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.visit_info_.IsDefault()) {
    _impl_.visit_info_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:milvus.proto.feder.FederSegmentSearchResult.visit_info)
}

// -------------------------------------------------------------------

// ListIndexedSegmentRequest

// .milvus.proto.common.MsgBase base = 1;
inline bool ListIndexedSegmentRequest::_internal_has_base() const {
  return this != internal_default_instance() && _impl_.base_ != nullptr;
}
inline bool ListIndexedSegmentRequest::has_base() const {
  return _internal_has_base();
}
inline const ::milvus::proto::common::MsgBase& ListIndexedSegmentRequest::_internal_base() const {
  const ::milvus::proto::common::MsgBase* p = _impl_.base_;
  return p != nullptr ? *p : reinterpret_cast<const ::milvus::proto::common::MsgBase&>(
      ::milvus::proto::common::_MsgBase_default_instance_);
}
inline const ::milvus::proto::common::MsgBase& ListIndexedSegmentRequest::base() const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.ListIndexedSegmentRequest.base)
  return _internal_base();
}
inline void ListIndexedSegmentRequest::unsafe_arena_set_allocated_base(
    ::milvus::proto::common::MsgBase* base) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.base_);
  }
  _impl_.base_ = base;
  if (base) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:milvus.proto.feder.ListIndexedSegmentRequest.base)
}
inline ::milvus::proto::common::MsgBase* ListIndexedSegmentRequest::release_base() {
  
  ::milvus::proto::common::MsgBase* temp = _impl_.base_;
  _impl_.base_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::milvus::proto::common::MsgBase* ListIndexedSegmentRequest::unsafe_arena_release_base() {
  // @@protoc_insertion_point(field_release:milvus.proto.feder.ListIndexedSegmentRequest.base)
  
  ::milvus::proto::common::MsgBase* temp = _impl_.base_;
  _impl_.base_ = nullptr;
  return temp;
}
inline ::milvus::proto::common::MsgBase* ListIndexedSegmentRequest::_internal_mutable_base() {
  
  if (_impl_.base_ == nullptr) {
    auto* p = CreateMaybeMessage<::milvus::proto::common::MsgBase>(GetArenaForAllocation());
    _impl_.base_ = p;
  }
  return _impl_.base_;
}
inline ::milvus::proto::common::MsgBase* ListIndexedSegmentRequest::mutable_base() {
  ::milvus::proto::common::MsgBase* _msg = _internal_mutable_base();
  // @@protoc_insertion_point(field_mutable:milvus.proto.feder.ListIndexedSegmentRequest.base)
  return _msg;
}
inline void ListIndexedSegmentRequest::set_allocated_base(::milvus::proto::common::MsgBase* base) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.base_);
  }
  if (base) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(base));
    if (message_arena != submessage_arena) {
      base = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, base, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.base_ = base;
  // @@protoc_insertion_point(field_set_allocated:milvus.proto.feder.ListIndexedSegmentRequest.base)
}

// string collection_name = 2;
inline void ListIndexedSegmentRequest::clear_collection_name() {
  _impl_.collection_name_.ClearToEmpty();
}
inline const std::string& ListIndexedSegmentRequest::collection_name() const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.ListIndexedSegmentRequest.collection_name)
  return _internal_collection_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ListIndexedSegmentRequest::set_collection_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.collection_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:milvus.proto.feder.ListIndexedSegmentRequest.collection_name)
}
inline std::string* ListIndexedSegmentRequest::mutable_collection_name() {
  std::string* _s = _internal_mutable_collection_name();
  // @@protoc_insertion_point(field_mutable:milvus.proto.feder.ListIndexedSegmentRequest.collection_name)
  return _s;
}
inline const std::string& ListIndexedSegmentRequest::_internal_collection_name() const {
  return _impl_.collection_name_.Get();
}
inline void ListIndexedSegmentRequest::_internal_set_collection_name(const std::string& value) {
  
  _impl_.collection_name_.Set(value, GetArenaForAllocation());
}
inline std::string* ListIndexedSegmentRequest::_internal_mutable_collection_name() {
  
  return _impl_.collection_name_.Mutable(GetArenaForAllocation());
}
inline std::string* ListIndexedSegmentRequest::release_collection_name() {
  // @@protoc_insertion_point(field_release:milvus.proto.feder.ListIndexedSegmentRequest.collection_name)
  return _impl_.collection_name_.Release();
}
inline void ListIndexedSegmentRequest::set_allocated_collection_name(std::string* collection_name) {
  if (collection_name != nullptr) {
    
  } else {
    
  }
  _impl_.collection_name_.SetAllocated(collection_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.collection_name_.IsDefault()) {
    _impl_.collection_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:milvus.proto.feder.ListIndexedSegmentRequest.collection_name)
}

// string index_name = 3;
inline void ListIndexedSegmentRequest::clear_index_name() {
  _impl_.index_name_.ClearToEmpty();
}
inline const std::string& ListIndexedSegmentRequest::index_name() const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.ListIndexedSegmentRequest.index_name)
  return _internal_index_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ListIndexedSegmentRequest::set_index_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.index_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:milvus.proto.feder.ListIndexedSegmentRequest.index_name)
}
inline std::string* ListIndexedSegmentRequest::mutable_index_name() {
  std::string* _s = _internal_mutable_index_name();
  // @@protoc_insertion_point(field_mutable:milvus.proto.feder.ListIndexedSegmentRequest.index_name)
  return _s;
}
inline const std::string& ListIndexedSegmentRequest::_internal_index_name() const {
  return _impl_.index_name_.Get();
}
inline void ListIndexedSegmentRequest::_internal_set_index_name(const std::string& value) {
  
  _impl_.index_name_.Set(value, GetArenaForAllocation());
}
inline std::string* ListIndexedSegmentRequest::_internal_mutable_index_name() {
  
  return _impl_.index_name_.Mutable(GetArenaForAllocation());
}
inline std::string* ListIndexedSegmentRequest::release_index_name() {
  // @@protoc_insertion_point(field_release:milvus.proto.feder.ListIndexedSegmentRequest.index_name)
  return _impl_.index_name_.Release();
}
inline void ListIndexedSegmentRequest::set_allocated_index_name(std::string* index_name) {
  if (index_name != nullptr) {
    
  } else {
    
  }
  _impl_.index_name_.SetAllocated(index_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.index_name_.IsDefault()) {
    _impl_.index_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:milvus.proto.feder.ListIndexedSegmentRequest.index_name)
}

// -------------------------------------------------------------------

// ListIndexedSegmentResponse

// .milvus.proto.common.Status status = 1;
inline bool ListIndexedSegmentResponse::_internal_has_status() const {
  return this != internal_default_instance() && _impl_.status_ != nullptr;
}
inline bool ListIndexedSegmentResponse::has_status() const {
  return _internal_has_status();
}
inline const ::milvus::proto::common::Status& ListIndexedSegmentResponse::_internal_status() const {
  const ::milvus::proto::common::Status* p = _impl_.status_;
  return p != nullptr ? *p : reinterpret_cast<const ::milvus::proto::common::Status&>(
      ::milvus::proto::common::_Status_default_instance_);
}
inline const ::milvus::proto::common::Status& ListIndexedSegmentResponse::status() const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.ListIndexedSegmentResponse.status)
  return _internal_status();
}
inline void ListIndexedSegmentResponse::unsafe_arena_set_allocated_status(
    ::milvus::proto::common::Status* status) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.status_);
  }
  _impl_.status_ = status;
  if (status) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:milvus.proto.feder.ListIndexedSegmentResponse.status)
}
inline ::milvus::proto::common::Status* ListIndexedSegmentResponse::release_status() {
  
  ::milvus::proto::common::Status* temp = _impl_.status_;
  _impl_.status_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::milvus::proto::common::Status* ListIndexedSegmentResponse::unsafe_arena_release_status() {
  // @@protoc_insertion_point(field_release:milvus.proto.feder.ListIndexedSegmentResponse.status)
  
  ::milvus::proto::common::Status* temp = _impl_.status_;
  _impl_.status_ = nullptr;
  return temp;
}
inline ::milvus::proto::common::Status* ListIndexedSegmentResponse::_internal_mutable_status() {
  
  if (_impl_.status_ == nullptr) {
    auto* p = CreateMaybeMessage<::milvus::proto::common::Status>(GetArenaForAllocation());
    _impl_.status_ = p;
  }
  return _impl_.status_;
}
inline ::milvus::proto::common::Status* ListIndexedSegmentResponse::mutable_status() {
  ::milvus::proto::common::Status* _msg = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:milvus.proto.feder.ListIndexedSegmentResponse.status)
  return _msg;
}
inline void ListIndexedSegmentResponse::set_allocated_status(::milvus::proto::common::Status* status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.status_);
  }
  if (status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(status));
    if (message_arena != submessage_arena) {
      status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, status, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.status_ = status;
  // @@protoc_insertion_point(field_set_allocated:milvus.proto.feder.ListIndexedSegmentResponse.status)
}

// repeated int64 segmentIDs = 2;
inline int ListIndexedSegmentResponse::_internal_segmentids_size() const {
  return _impl_.segmentids_.size();
}
inline int ListIndexedSegmentResponse::segmentids_size() const {
  return _internal_segmentids_size();
}
inline void ListIndexedSegmentResponse::clear_segmentids() {
  _impl_.segmentids_.Clear();
}
inline int64_t ListIndexedSegmentResponse::_internal_segmentids(int index) const {
  return _impl_.segmentids_.Get(index);
}
inline int64_t ListIndexedSegmentResponse::segmentids(int index) const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.ListIndexedSegmentResponse.segmentIDs)
  return _internal_segmentids(index);
}
inline void ListIndexedSegmentResponse::set_segmentids(int index, int64_t value) {
  _impl_.segmentids_.Set(index, value);
  // @@protoc_insertion_point(field_set:milvus.proto.feder.ListIndexedSegmentResponse.segmentIDs)
}
inline void ListIndexedSegmentResponse::_internal_add_segmentids(int64_t value) {
  _impl_.segmentids_.Add(value);
}
inline void ListIndexedSegmentResponse::add_segmentids(int64_t value) {
  _internal_add_segmentids(value);
  // @@protoc_insertion_point(field_add:milvus.proto.feder.ListIndexedSegmentResponse.segmentIDs)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
ListIndexedSegmentResponse::_internal_segmentids() const {
  return _impl_.segmentids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
ListIndexedSegmentResponse::segmentids() const {
  // @@protoc_insertion_point(field_list:milvus.proto.feder.ListIndexedSegmentResponse.segmentIDs)
  return _internal_segmentids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
ListIndexedSegmentResponse::_internal_mutable_segmentids() {
  return &_impl_.segmentids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
ListIndexedSegmentResponse::mutable_segmentids() {
  // @@protoc_insertion_point(field_mutable_list:milvus.proto.feder.ListIndexedSegmentResponse.segmentIDs)
  return _internal_mutable_segmentids();
}

// -------------------------------------------------------------------

// DescribeSegmentIndexDataRequest

// .milvus.proto.common.MsgBase base = 1;
inline bool DescribeSegmentIndexDataRequest::_internal_has_base() const {
  return this != internal_default_instance() && _impl_.base_ != nullptr;
}
inline bool DescribeSegmentIndexDataRequest::has_base() const {
  return _internal_has_base();
}
inline const ::milvus::proto::common::MsgBase& DescribeSegmentIndexDataRequest::_internal_base() const {
  const ::milvus::proto::common::MsgBase* p = _impl_.base_;
  return p != nullptr ? *p : reinterpret_cast<const ::milvus::proto::common::MsgBase&>(
      ::milvus::proto::common::_MsgBase_default_instance_);
}
inline const ::milvus::proto::common::MsgBase& DescribeSegmentIndexDataRequest::base() const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.DescribeSegmentIndexDataRequest.base)
  return _internal_base();
}
inline void DescribeSegmentIndexDataRequest::unsafe_arena_set_allocated_base(
    ::milvus::proto::common::MsgBase* base) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.base_);
  }
  _impl_.base_ = base;
  if (base) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:milvus.proto.feder.DescribeSegmentIndexDataRequest.base)
}
inline ::milvus::proto::common::MsgBase* DescribeSegmentIndexDataRequest::release_base() {
  
  ::milvus::proto::common::MsgBase* temp = _impl_.base_;
  _impl_.base_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::milvus::proto::common::MsgBase* DescribeSegmentIndexDataRequest::unsafe_arena_release_base() {
  // @@protoc_insertion_point(field_release:milvus.proto.feder.DescribeSegmentIndexDataRequest.base)
  
  ::milvus::proto::common::MsgBase* temp = _impl_.base_;
  _impl_.base_ = nullptr;
  return temp;
}
inline ::milvus::proto::common::MsgBase* DescribeSegmentIndexDataRequest::_internal_mutable_base() {
  
  if (_impl_.base_ == nullptr) {
    auto* p = CreateMaybeMessage<::milvus::proto::common::MsgBase>(GetArenaForAllocation());
    _impl_.base_ = p;
  }
  return _impl_.base_;
}
inline ::milvus::proto::common::MsgBase* DescribeSegmentIndexDataRequest::mutable_base() {
  ::milvus::proto::common::MsgBase* _msg = _internal_mutable_base();
  // @@protoc_insertion_point(field_mutable:milvus.proto.feder.DescribeSegmentIndexDataRequest.base)
  return _msg;
}
inline void DescribeSegmentIndexDataRequest::set_allocated_base(::milvus::proto::common::MsgBase* base) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.base_);
  }
  if (base) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(base));
    if (message_arena != submessage_arena) {
      base = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, base, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.base_ = base;
  // @@protoc_insertion_point(field_set_allocated:milvus.proto.feder.DescribeSegmentIndexDataRequest.base)
}

// string collection_name = 2;
inline void DescribeSegmentIndexDataRequest::clear_collection_name() {
  _impl_.collection_name_.ClearToEmpty();
}
inline const std::string& DescribeSegmentIndexDataRequest::collection_name() const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.DescribeSegmentIndexDataRequest.collection_name)
  return _internal_collection_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DescribeSegmentIndexDataRequest::set_collection_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.collection_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:milvus.proto.feder.DescribeSegmentIndexDataRequest.collection_name)
}
inline std::string* DescribeSegmentIndexDataRequest::mutable_collection_name() {
  std::string* _s = _internal_mutable_collection_name();
  // @@protoc_insertion_point(field_mutable:milvus.proto.feder.DescribeSegmentIndexDataRequest.collection_name)
  return _s;
}
inline const std::string& DescribeSegmentIndexDataRequest::_internal_collection_name() const {
  return _impl_.collection_name_.Get();
}
inline void DescribeSegmentIndexDataRequest::_internal_set_collection_name(const std::string& value) {
  
  _impl_.collection_name_.Set(value, GetArenaForAllocation());
}
inline std::string* DescribeSegmentIndexDataRequest::_internal_mutable_collection_name() {
  
  return _impl_.collection_name_.Mutable(GetArenaForAllocation());
}
inline std::string* DescribeSegmentIndexDataRequest::release_collection_name() {
  // @@protoc_insertion_point(field_release:milvus.proto.feder.DescribeSegmentIndexDataRequest.collection_name)
  return _impl_.collection_name_.Release();
}
inline void DescribeSegmentIndexDataRequest::set_allocated_collection_name(std::string* collection_name) {
  if (collection_name != nullptr) {
    
  } else {
    
  }
  _impl_.collection_name_.SetAllocated(collection_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.collection_name_.IsDefault()) {
    _impl_.collection_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:milvus.proto.feder.DescribeSegmentIndexDataRequest.collection_name)
}

// string index_name = 3;
inline void DescribeSegmentIndexDataRequest::clear_index_name() {
  _impl_.index_name_.ClearToEmpty();
}
inline const std::string& DescribeSegmentIndexDataRequest::index_name() const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.DescribeSegmentIndexDataRequest.index_name)
  return _internal_index_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DescribeSegmentIndexDataRequest::set_index_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.index_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:milvus.proto.feder.DescribeSegmentIndexDataRequest.index_name)
}
inline std::string* DescribeSegmentIndexDataRequest::mutable_index_name() {
  std::string* _s = _internal_mutable_index_name();
  // @@protoc_insertion_point(field_mutable:milvus.proto.feder.DescribeSegmentIndexDataRequest.index_name)
  return _s;
}
inline const std::string& DescribeSegmentIndexDataRequest::_internal_index_name() const {
  return _impl_.index_name_.Get();
}
inline void DescribeSegmentIndexDataRequest::_internal_set_index_name(const std::string& value) {
  
  _impl_.index_name_.Set(value, GetArenaForAllocation());
}
inline std::string* DescribeSegmentIndexDataRequest::_internal_mutable_index_name() {
  
  return _impl_.index_name_.Mutable(GetArenaForAllocation());
}
inline std::string* DescribeSegmentIndexDataRequest::release_index_name() {
  // @@protoc_insertion_point(field_release:milvus.proto.feder.DescribeSegmentIndexDataRequest.index_name)
  return _impl_.index_name_.Release();
}
inline void DescribeSegmentIndexDataRequest::set_allocated_index_name(std::string* index_name) {
  if (index_name != nullptr) {
    
  } else {
    
  }
  _impl_.index_name_.SetAllocated(index_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.index_name_.IsDefault()) {
    _impl_.index_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:milvus.proto.feder.DescribeSegmentIndexDataRequest.index_name)
}

// repeated int64 segmentsIDs = 4;
inline int DescribeSegmentIndexDataRequest::_internal_segmentsids_size() const {
  return _impl_.segmentsids_.size();
}
inline int DescribeSegmentIndexDataRequest::segmentsids_size() const {
  return _internal_segmentsids_size();
}
inline void DescribeSegmentIndexDataRequest::clear_segmentsids() {
  _impl_.segmentsids_.Clear();
}
inline int64_t DescribeSegmentIndexDataRequest::_internal_segmentsids(int index) const {
  return _impl_.segmentsids_.Get(index);
}
inline int64_t DescribeSegmentIndexDataRequest::segmentsids(int index) const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.DescribeSegmentIndexDataRequest.segmentsIDs)
  return _internal_segmentsids(index);
}
inline void DescribeSegmentIndexDataRequest::set_segmentsids(int index, int64_t value) {
  _impl_.segmentsids_.Set(index, value);
  // @@protoc_insertion_point(field_set:milvus.proto.feder.DescribeSegmentIndexDataRequest.segmentsIDs)
}
inline void DescribeSegmentIndexDataRequest::_internal_add_segmentsids(int64_t value) {
  _impl_.segmentsids_.Add(value);
}
inline void DescribeSegmentIndexDataRequest::add_segmentsids(int64_t value) {
  _internal_add_segmentsids(value);
  // @@protoc_insertion_point(field_add:milvus.proto.feder.DescribeSegmentIndexDataRequest.segmentsIDs)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
DescribeSegmentIndexDataRequest::_internal_segmentsids() const {
  return _impl_.segmentsids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >&
DescribeSegmentIndexDataRequest::segmentsids() const {
  // @@protoc_insertion_point(field_list:milvus.proto.feder.DescribeSegmentIndexDataRequest.segmentsIDs)
  return _internal_segmentsids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
DescribeSegmentIndexDataRequest::_internal_mutable_segmentsids() {
  return &_impl_.segmentsids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int64_t >*
DescribeSegmentIndexDataRequest::mutable_segmentsids() {
  // @@protoc_insertion_point(field_mutable_list:milvus.proto.feder.DescribeSegmentIndexDataRequest.segmentsIDs)
  return _internal_mutable_segmentsids();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// DescribeSegmentIndexDataResponse

// .milvus.proto.common.Status status = 1;
inline bool DescribeSegmentIndexDataResponse::_internal_has_status() const {
  return this != internal_default_instance() && _impl_.status_ != nullptr;
}
inline bool DescribeSegmentIndexDataResponse::has_status() const {
  return _internal_has_status();
}
inline const ::milvus::proto::common::Status& DescribeSegmentIndexDataResponse::_internal_status() const {
  const ::milvus::proto::common::Status* p = _impl_.status_;
  return p != nullptr ? *p : reinterpret_cast<const ::milvus::proto::common::Status&>(
      ::milvus::proto::common::_Status_default_instance_);
}
inline const ::milvus::proto::common::Status& DescribeSegmentIndexDataResponse::status() const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.DescribeSegmentIndexDataResponse.status)
  return _internal_status();
}
inline void DescribeSegmentIndexDataResponse::unsafe_arena_set_allocated_status(
    ::milvus::proto::common::Status* status) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.status_);
  }
  _impl_.status_ = status;
  if (status) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:milvus.proto.feder.DescribeSegmentIndexDataResponse.status)
}
inline ::milvus::proto::common::Status* DescribeSegmentIndexDataResponse::release_status() {
  
  ::milvus::proto::common::Status* temp = _impl_.status_;
  _impl_.status_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::milvus::proto::common::Status* DescribeSegmentIndexDataResponse::unsafe_arena_release_status() {
  // @@protoc_insertion_point(field_release:milvus.proto.feder.DescribeSegmentIndexDataResponse.status)
  
  ::milvus::proto::common::Status* temp = _impl_.status_;
  _impl_.status_ = nullptr;
  return temp;
}
inline ::milvus::proto::common::Status* DescribeSegmentIndexDataResponse::_internal_mutable_status() {
  
  if (_impl_.status_ == nullptr) {
    auto* p = CreateMaybeMessage<::milvus::proto::common::Status>(GetArenaForAllocation());
    _impl_.status_ = p;
  }
  return _impl_.status_;
}
inline ::milvus::proto::common::Status* DescribeSegmentIndexDataResponse::mutable_status() {
  ::milvus::proto::common::Status* _msg = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:milvus.proto.feder.DescribeSegmentIndexDataResponse.status)
  return _msg;
}
inline void DescribeSegmentIndexDataResponse::set_allocated_status(::milvus::proto::common::Status* status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.status_);
  }
  if (status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(status));
    if (message_arena != submessage_arena) {
      status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, status, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.status_ = status;
  // @@protoc_insertion_point(field_set_allocated:milvus.proto.feder.DescribeSegmentIndexDataResponse.status)
}

// map<int64, .milvus.proto.feder.SegmentIndexData> index_data = 2;
inline int DescribeSegmentIndexDataResponse::_internal_index_data_size() const {
  return _impl_.index_data_.size();
}
inline int DescribeSegmentIndexDataResponse::index_data_size() const {
  return _internal_index_data_size();
}
inline void DescribeSegmentIndexDataResponse::clear_index_data() {
  _impl_.index_data_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int64_t, ::milvus::proto::feder::SegmentIndexData >&
DescribeSegmentIndexDataResponse::_internal_index_data() const {
  return _impl_.index_data_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int64_t, ::milvus::proto::feder::SegmentIndexData >&
DescribeSegmentIndexDataResponse::index_data() const {
  // @@protoc_insertion_point(field_map:milvus.proto.feder.DescribeSegmentIndexDataResponse.index_data)
  return _internal_index_data();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int64_t, ::milvus::proto::feder::SegmentIndexData >*
DescribeSegmentIndexDataResponse::_internal_mutable_index_data() {
  return _impl_.index_data_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int64_t, ::milvus::proto::feder::SegmentIndexData >*
DescribeSegmentIndexDataResponse::mutable_index_data() {
  // @@protoc_insertion_point(field_mutable_map:milvus.proto.feder.DescribeSegmentIndexDataResponse.index_data)
  return _internal_mutable_index_data();
}

// repeated .milvus.proto.common.KeyValuePair index_params = 3;
inline int DescribeSegmentIndexDataResponse::_internal_index_params_size() const {
  return _impl_.index_params_.size();
}
inline int DescribeSegmentIndexDataResponse::index_params_size() const {
  return _internal_index_params_size();
}
inline ::milvus::proto::common::KeyValuePair* DescribeSegmentIndexDataResponse::mutable_index_params(int index) {
  // @@protoc_insertion_point(field_mutable:milvus.proto.feder.DescribeSegmentIndexDataResponse.index_params)
  return _impl_.index_params_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::milvus::proto::common::KeyValuePair >*
DescribeSegmentIndexDataResponse::mutable_index_params() {
  // @@protoc_insertion_point(field_mutable_list:milvus.proto.feder.DescribeSegmentIndexDataResponse.index_params)
  return &_impl_.index_params_;
}
inline const ::milvus::proto::common::KeyValuePair& DescribeSegmentIndexDataResponse::_internal_index_params(int index) const {
  return _impl_.index_params_.Get(index);
}
inline const ::milvus::proto::common::KeyValuePair& DescribeSegmentIndexDataResponse::index_params(int index) const {
  // @@protoc_insertion_point(field_get:milvus.proto.feder.DescribeSegmentIndexDataResponse.index_params)
  return _internal_index_params(index);
}
inline ::milvus::proto::common::KeyValuePair* DescribeSegmentIndexDataResponse::_internal_add_index_params() {
  return _impl_.index_params_.Add();
}
inline ::milvus::proto::common::KeyValuePair* DescribeSegmentIndexDataResponse::add_index_params() {
  ::milvus::proto::common::KeyValuePair* _add = _internal_add_index_params();
  // @@protoc_insertion_point(field_add:milvus.proto.feder.DescribeSegmentIndexDataResponse.index_params)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::milvus::proto::common::KeyValuePair >&
DescribeSegmentIndexDataResponse::index_params() const {
  // @@protoc_insertion_point(field_list:milvus.proto.feder.DescribeSegmentIndexDataResponse.index_params)
  return _impl_.index_params_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace feder
}  // namespace proto
}  // namespace milvus

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_feder_2eproto
